spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: password
    url: jdbc:h2:mem:adm_videos_test;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2